import Essential4Tello
from time import sleep
tl = Essential4Tello.Essential4Tello.InitialTello()
# L/R， F/B， U/D，Yaw
tl.send_rc_control(50, 0, 0, 0)
sleep(2)
tl.send_rc_control(-50, 0, 0, 0)
sleep(2)
tl.send_rc_control(0, 50, 0, 0)
sleep(2)
tl.send_rc_control(0, -50, 0, 0)
sleep(2)
tl.send_rc_control(0, 0, 20, 0)
sleep(2)
tl.send_rc_control(0, 0, -20, 0)
sleep(2)
tl.send_rc_control(0, 0, 0, 90)
sleep(2)
tl.send_rc_control(0, 0, 0, -90)
sleep(2)
tl.send_rc_control(0, 0, 0, 0)
tl.land()
print(tl.get_battery())
print(tl.get_temperature())
print(tl.get_flight_time())
